# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: shino.io
email: huynvk@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Ứng dụng trợ lý cho mẹ bầu và chăm sóc em bé. Theo dõi sức khoẻ của mẹ và bé, giới thiệu thông tin chọn lọc cho mẹ,
  gợi ý những việc cần làm. Miễn phí trên google play và app store
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://shino.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: huynvk
github_username: huynvk

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
sass:
  sass_dir: _sass
defaults:
  - scope:
      path: "assets/images"
    values:
      image: true
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
